"""
User Interface Components Module

Contains helper functions that render HTML UI components and Markdown
text blocks for use in the Gradio fronted.
"""
from typing import Dict, Any

def format_triage_badge(urgency: str, label: str) -> str:
    """
    Returns an HTML div with a color-coded border and emoji corresponding to the urgency.
    
    Args:
        urgency (str): "green", "yellow", or "red"
        label (str): Text description for the badge
        
    Returns:
        str: Formatted HTML block
    """
    urgency = urgency.lower().strip()
    
    colors = {
        "green": ("#22c55e", "🟢"),
        "yellow": ("#f59e0b", "🟡"),
        "red": ("#ef4444", "🔴")
    }
    
    color, emoji = colors.get(urgency, ("#9ca3af", "⚪"))
    
    html = f"""
    <div style="border: 2px solid {color}; border-radius: 8px; padding: 15px; margin: 10px 0; background-color: {color}10; display: flex; align-items: center; gap: 10px;">
        <span style="font-size: 24px;">{emoji}</span>
        <span style="font-size: 18px; font-weight: bold; color: {color};">{label}</span>
    </div>
    """
    return html

def format_assessment_summary(assessment: Dict[str, Any]) -> str:
    """
    Returns a markdown formatted string of the MedGemma initial assessment results.
    
    Args:
        assessment (Dict): The parsed JSON from the initial assessment.
        
    Returns:
        str: Markdown representation of the assessment.
    """
    if "error" in assessment:
        return f"**Error parsing assessment:** {assessment.get('error', 'Unknown error')}\n\nRaw output: `{assessment.get('raw', '')}`"
        
    condition = assessment.get("condition_category", "Unknown").replace("_", " ").title()
    confidence = assessment.get("confidence", "Unknown").title()
    features = assessment.get("key_features_observed", [])
    features_list = "\n".join([f"- {feat}" for feat in features]) if isinstance(features, list) else str(features)
    
    md = f"""### AI Visual Assessment
**Likely Condition:** {condition}
**Model Confidence:** {confidence}

**Key Features Observed:**
{features_list}
"""
    return md

def format_referral_note(triage_result: Dict[str, Any]) -> str:
    """
    Returns a formatted markdown referral note string for final output.
    
    Args:
        triage_result (Dict): The parsed JSON from the final triage generation.
        
    Returns:
        str: Rendered markdown note.
    """
    if "error" in triage_result:
        return f"**Error parsing triage result:** {triage_result.get('error', 'Unknown error')}\n\nRaw output: `{triage_result.get('raw', '')}`"
        
    rationale = triage_result.get("triage_rationale", "No rationale provided.")
    instructions = triage_result.get("patient_instructions", "No instructions provided.")
    note = triage_result.get("referral_note", {})
    
    note_md = f"""### Triage Details & Referral Note
**Decision Rationale:**
{rationale}

**Patient Instructions:**
{instructions}

---

#### Formal Referral Note
***Chief Complaint:*** {note.get('chief_complaint', 'N/A')}
***Clinical Suspicion:*** {note.get('clinical_suspicion', 'N/A')}
***Timeline Notes:*** {note.get('timeline_notes', 'N/A')}
***Recommended Action:*** {note.get('recommended_action', 'N/A')}

---
*Disclaimer: Generated by DermScreen AI based on structured photograph analysis. This is a clinical decision support tool and does not constitute a definitive medical diagnosis.*
"""
    return note_md
